version: '3'
services:
  app:
    build: ./docker/php
    container_name: skillup_php
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.17
    container_name: skillup_nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/skillup.local.conf:/etc/nginx/conf.d/skillup.local.conf
    depends_on:
      - app
#  mysql:
#    image: mysql:8
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root_pwd