CREATE TABLE MYSQL.USERS (
ID              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
USERNAME        VARCHAR(50) NOT NULL,
PASSWORD        VARCHAR(32) NOT NULL,
DATE_CREATED    TIMESTAMP NOT NULL,
LM_DATE         TIMESTAMP NOT NULL
);